# Generated by Django 5.1.5 on 2025-01-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problem_userproblem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='description',
            new_name='description_file',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='starter_file',
            new_name='starter_code',
        ),
    ]
